// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: leads.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_leads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lead) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lead) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Lead) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Lead) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Lead) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Lead) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Lead) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_leads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLeadRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateLeadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateLeadRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadResponse) Reset() {
	*x = CreateLeadResponse{}
	mi := &file_leads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadResponse) ProtoMessage() {}

func (x *CreateLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadResponse.ProtoReflect.Descriptor instead.
func (*CreateLeadResponse) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLeadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLeadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadRequest) Reset() {
	*x = GetLeadRequest{}
	mi := &file_leads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadRequest) ProtoMessage() {}

func (x *GetLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadRequest.ProtoReflect.Descriptor instead.
func (*GetLeadRequest) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadResponse) Reset() {
	*x = GetLeadResponse{}
	mi := &file_leads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadResponse) ProtoMessage() {}

func (x *GetLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadResponse.ProtoReflect.Descriptor instead.
func (*GetLeadResponse) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type UpdateLeadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadStatusRequest) Reset() {
	*x = UpdateLeadStatusRequest{}
	mi := &file_leads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadStatusRequest) ProtoMessage() {}

func (x *UpdateLeadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadStatusRequest) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLeadStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLeadStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateLeadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadStatusResponse) Reset() {
	*x = UpdateLeadStatusResponse{}
	mi := &file_leads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadStatusResponse) ProtoMessage() {}

func (x *UpdateLeadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateLeadStatusResponse) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLeadStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateLeadStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLeadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest) Reset() {
	*x = ListLeadsRequest{}
	mi := &file_leads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest) ProtoMessage() {}

func (x *ListLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{7}
}

func (x *ListLeadsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListLeadsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListLeadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Lead                `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsResponse) Reset() {
	*x = ListLeadsResponse{}
	mi := &file_leads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsResponse) ProtoMessage() {}

func (x *ListLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsResponse) Descriptor() ([]byte, []int) {
	return file_leads_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeadsResponse) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

var File_leads_proto protoreflect.FileDescriptor

const file_leads_proto_rawDesc = "" +
	"\n" +
	"\vleads.proto\x12\x04lead\"\xc4\x01\n" +
	"\x04Lead\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"k\n" +
	"\x11CreateLeadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"<\n" +
	"\x12CreateLeadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\" \n" +
	"\x0eGetLeadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetLeadResponse\x12\x1e\n" +
	"\x04lead\x18\x01 \x01(\v2\n" +
	".lead.LeadR\x04lead\"A\n" +
	"\x17UpdateLeadStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x18UpdateLeadStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x10ListLeadsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"5\n" +
	"\x11ListLeadsResponse\x12 \n" +
	"\x05leads\x18\x01 \x03(\v2\n" +
	".lead.LeadR\x05leads2\x97\x02\n" +
	"\vLeadService\x12?\n" +
	"\n" +
	"CreateLead\x12\x17.lead.CreateLeadRequest\x1a\x18.lead.CreateLeadResponse\x126\n" +
	"\aGetLead\x12\x14.lead.GetLeadRequest\x1a\x15.lead.GetLeadResponse\x12Q\n" +
	"\x10UpdateLeadStatus\x12\x1d.lead.UpdateLeadStatusRequest\x1a\x1e.lead.UpdateLeadStatusResponse\x12<\n" +
	"\tListLeads\x12\x16.lead.ListLeadsRequest\x1a\x17.lead.ListLeadsResponseB\n" +
	"Z\bleads/pbb\x06proto3"

var (
	file_leads_proto_rawDescOnce sync.Once
	file_leads_proto_rawDescData []byte
)

func file_leads_proto_rawDescGZIP() []byte {
	file_leads_proto_rawDescOnce.Do(func() {
		file_leads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leads_proto_rawDesc), len(file_leads_proto_rawDesc)))
	})
	return file_leads_proto_rawDescData
}

var file_leads_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_leads_proto_goTypes = []any{
	(*Lead)(nil),                     // 0: lead.Lead
	(*CreateLeadRequest)(nil),        // 1: lead.CreateLeadRequest
	(*CreateLeadResponse)(nil),       // 2: lead.CreateLeadResponse
	(*GetLeadRequest)(nil),           // 3: lead.GetLeadRequest
	(*GetLeadResponse)(nil),          // 4: lead.GetLeadResponse
	(*UpdateLeadStatusRequest)(nil),  // 5: lead.UpdateLeadStatusRequest
	(*UpdateLeadStatusResponse)(nil), // 6: lead.UpdateLeadStatusResponse
	(*ListLeadsRequest)(nil),         // 7: lead.ListLeadsRequest
	(*ListLeadsResponse)(nil),        // 8: lead.ListLeadsResponse
}
var file_leads_proto_depIdxs = []int32{
	0, // 0: lead.GetLeadResponse.lead:type_name -> lead.Lead
	0, // 1: lead.ListLeadsResponse.leads:type_name -> lead.Lead
	1, // 2: lead.LeadService.CreateLead:input_type -> lead.CreateLeadRequest
	3, // 3: lead.LeadService.GetLead:input_type -> lead.GetLeadRequest
	5, // 4: lead.LeadService.UpdateLeadStatus:input_type -> lead.UpdateLeadStatusRequest
	7, // 5: lead.LeadService.ListLeads:input_type -> lead.ListLeadsRequest
	2, // 6: lead.LeadService.CreateLead:output_type -> lead.CreateLeadResponse
	4, // 7: lead.LeadService.GetLead:output_type -> lead.GetLeadResponse
	6, // 8: lead.LeadService.UpdateLeadStatus:output_type -> lead.UpdateLeadStatusResponse
	8, // 9: lead.LeadService.ListLeads:output_type -> lead.ListLeadsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_leads_proto_init() }
func file_leads_proto_init() {
	if File_leads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leads_proto_rawDesc), len(file_leads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leads_proto_goTypes,
		DependencyIndexes: file_leads_proto_depIdxs,
		MessageInfos:      file_leads_proto_msgTypes,
	}.Build()
	File_leads_proto = out.File
	file_leads_proto_goTypes = nil
	file_leads_proto_depIdxs = nil
}
